--JÁ ESTÁ CRIADA NA BASE CNAB, BASTA EXECUTAR
--EXEC EXPORTA_CNAB_PARA_STG
CREATE   PROCEDURE EXPORTA_CNAB_PARA_STG
    @DATA DATETIME = NULL,
    @EXPORTADO VARCHAR(1) = 'N'
AS
BEGIN
    SET NOCOUNT ON;
	DECLARE @QTD_EXPORTADOS INT = 0;


    -- Se a data não for passada, pega a data atual
    IF @DATA IS NULL
        SET @DATA = convert(date,GETDATE());

    DECLARE @IDS_EXPORTAR TABLE (ID INT);

    -- Cursor para pegar IDs que serão exportados
    INSERT INTO @IDS_EXPORTAR (ID)
    SELECT ID
    FROM CNAB.dbo.USR_CRRET
    WHERE DTINCLUIU <= @DATA
      AND exportado = @EXPORTADO;
    
    SELECT @QTD_EXPORTADOS = COUNT(*) FROM @IDS_EXPORTAR;

    -- Verifica se tem algo para exportar
    IF EXISTS (SELECT 1 FROM @IDS_EXPORTAR)
    BEGIN
        DECLARE @ID_LOG INT;
        DECLARE @DATA_INICIO DATETIME = GETDATE();
        -- Cria o log principal
        INSERT INTO CNAB.dbo.Log_Exportacao (DATA_INICIO, STATUS, PARAM_DATA, PARAM_EXPORTADO,DATA_EXPORTACAO)
            VALUES (@DATA_INICIO, 'PROCESSANDO', @DATA, @EXPORTADO, @DATA);

        SET @ID_LOG = SCOPE_IDENTITY();

       
        -- Exporta USR_CRRET
		INSERT INTO STG_CNAB.dbo.USR_CRRET (ID, ARQUIVO, BANCO, DTINCLUIU)
		SELECT C.ID, C.ARQUIVO, C.BANCO, C.DTINCLUIU 
		FROM CNAB.dbo.USR_CRRET C
		WHERE C.ID IN (SELECT ID FROM @IDS_EXPORTAR)
		  AND NOT EXISTS (
		      SELECT 1
		      FROM STG_CNAB.dbo.USR_CRRET S
		      WHERE S.ID = C.ID
		  );
        
        -- Log de exportação USR_CRRET
        DECLARE @QTD_USR_CRRET INT;
        SELECT @QTD_USR_CRRET = COUNT(*) FROM STG_CNAB.dbo.USR_CRRET WHERE ID IN (SELECT ID FROM @IDS_EXPORTAR);

        INSERT INTO CNAB.dbo.Log_Exportacao_Tabelas (ID_LOG, TABELA, QTD_REGISTROS, STATUS)
        VALUES (@ID_LOG, 'USR_CRRET', @QTD_USR_CRRET, 'SUCESSO');
        
       
        --EXPORTA USR_OCORRENCIAS
		INSERT INTO STG_CNAB.dbo.USR_OCORRENCIAS (BANCO, COD_OCORRENCIA, DESCRICAO)
		SELECT O.BANCO, O.COD_OCORRENCIA, O.DESCRICAO
		FROM CNAB.dbo.USR_OCORRENCIAS O
		WHERE NOT EXISTS (
		    SELECT 1
		    FROM STG_CNAB.dbo.USR_OCORRENCIAS S
		    WHERE S.BANCO = O.BANCO AND S.COD_OCORRENCIA = O.COD_OCORRENCIA
		);

      
        --EXPORTAR USR_CRRET_BANCOS
		INSERT INTO STG_CNAB.DBO.USR_CRRET_BANCOS (ID_BANCO, COD_BANCO, NOME)
		SELECT B.ID_BANCO, B.COD_BANCO, B.NOME
		FROM CNAB.DBO.USR_CRRET_BANCOS B
		WHERE NOT EXISTS (
		    SELECT 1
		    FROM STG_CNAB.DBO.USR_CRRET_BANCOS S
		    WHERE S.ID_BANCO = B.ID_BANCO
		);

        
        -- Exporta USR_CRRET_BANCOS_C
        INSERT INTO STG_CNAB.dbo.USR_CRRET_BANCOS_C (BANCO, COD_BANCO,  DT_GERACAO,  ID_ARQUIVO, ID_BANCO, NOME_ARQUIVO, NUM_RETORNO)
        SELECT BANCO, COD_BANCO, DT_GERACAO, ID_ARQUIVO, ID_BANCO, NOME_ARQUIVO, NUM_RETORNO
        FROM CNAB.dbo.USR_CRRET_BANCOS_C
        WHERE ID_ARQUIVO IN (SELECT ID FROM @IDS_EXPORTAR);
        
        --Exporta USR_TARIFAS_CONTRATO
        INSERT INTO STG_CNAB.dbo.USR_TARIFAS_CONTRATO (BANCO, COD_TARIFA, DESC_TARIFA, VL_TARIFA)
		SELECT BANCO, COD_TARIFA, DESC_TARIFA, VL_TARIFA FROM USR_TARIFAS_CONTRATO ;

        -- Log de exportação USR_CRRET_BANCOS_C
        DECLARE @QTD_USR_CRRET_BANCOS_C INT;
        SELECT @QTD_USR_CRRET_BANCOS_C = COUNT(*) FROM STG_CNAB.dbo.USR_CRRET_BANCOS_C WHERE ID_ARQUIVO IN (SELECT ID FROM @IDS_EXPORTAR);

        INSERT INTO CNAB.dbo.Log_Exportacao_Tabelas (ID_LOG, TABELA, QTD_REGISTROS, STATUS)
        VALUES (@ID_LOG, 'USR_CRRET_BANCOS_C', @QTD_USR_CRRET_BANCOS_C, 'SUCESSO');

        -- Exporta USR_CRRET_BANCOS_L
        INSERT INTO STG_CNAB.dbo.USR_CRRET_BANCOS_L (ARQUIVO, BANCO, COD_OCORRENCIA, DESC_OCORRENCIA, DT_CREDITO, DT_GERACAO, DT_INCLUIUI, DT_OCORRENCIA, DT_VENCIMENTO,
                                                     ID, ID_DATA, JUROS_MORA, LANCAMENTO, N_DOCUMENTO, NOME_BANCO, NOSSO_NUMERO, TARIFA_COB, VL_PAGO, VL_TITULO)
        SELECT ARQUIVO, BANCO, COD_OCORRENCIA, DESC_OCORRENCIA, DT_CREDITO, DT_GERACAO, DT_INCLUIUI, DT_OCORRENCIA, DT_VENCIMENTO,
               ID, ID_DATA, JUROS_MORA, LANCAMENTO, N_DOCUMENTO, NOME_BANCO, NOSSO_NUMERO, TARIFA_COB, VL_PAGO, VL_TITULO
        FROM CNAB.dbo.USR_CRRET_BANCOS_L
        WHERE ID IN (SELECT ID FROM @IDS_EXPORTAR);
    
        -- Log de exportação USR_CRRET_BANCOS_L
        DECLARE @QTD_USR_CRRET_BANCOS_L INT;
        SELECT @QTD_USR_CRRET_BANCOS_L = COUNT(*) FROM STG_CNAB.dbo.USR_CRRET_BANCOS_L WHERE ID IN (SELECT ID FROM @IDS_EXPORTAR);

        INSERT INTO CNAB.dbo.Log_Exportacao_Tabelas (ID_LOG, TABELA, QTD_REGISTROS, STATUS)
        VALUES (@ID_LOG, 'USR_CRRET_BANCOS_L', @QTD_USR_CRRET_BANCOS_L, 'SUCESSO');

        -- Atualiza os registros como exportados
        UPDATE CNAB.dbo.USR_CRRET
        SET exportado = 'S'
        WHERE ID IN (SELECT ID FROM @IDS_EXPORTAR);
        
        UPDATE CNAB.dbo.Log_Exportacao
        SET STATUS = 'SUCESSO',
            DATA_FIM = GETDATE(),
            QTD_REGISTROS = @QTD_EXPORTADOS
        WHERE ID_LOG = @ID_LOG;
    END
END
