USE [DM_CNAB]
GO

/****** Object:  Table [dbo].[DIMTITULOS]    Script Date: 12/06/2025 18:22:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIMTITULOS](
	[ID_DUPLICATA] [int] NOT NULL,
	[DUPLICATA] [varchar](20) NULL,
	[NOSSO_NUMERO] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_DUPLICATA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

