USE [DM_CNAB]
GO

/****** Object:  Table [dbo].[DIMARQUIVO]    Script Date: 12/06/2025 18:21:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIMARQUIVO](
	[ID_ARQUIVO] [int] NOT NULL,
	[NOMEARQUIVO] [varchar](200) NULL,
	[ID_BANCO] [int] NULL,
	[CODIGO_BANCO] [varchar](3) NULL,
	[NOME_BANCO] [varchar](150) NULL,
	[DTGERACAO] [datetime] NULL,
	[DTINCLUIU] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ARQUIVO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [DM_CNAB]
GO

/****** Object:  Table [dbo].[DIMBANCOS]    Script Date: 12/06/2025 18:21:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIMBANCOS](
	[ID_BANCO] [int] NOT NULL,
	[CODIGO_BANCO] [varchar](3) NULL,
	[NOME_BANCO] [varchar](60) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_BANCO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [DM_CNAB]
GO

/****** Object:  Table [dbo].[DIMOCORRENCIAS]    Script Date: 12/06/2025 18:21:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIMOCORRENCIAS](
	[ID_OCORRENCIA] [int] NOT NULL,
	[ID_BANCO] [int] NULL,
	[COD_OCORRENCIA] [varchar](2) NULL,
	[DESC_OCORRENCIA] [varchar](150) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_OCORRENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [DM_CNAB]
GO

/****** Object:  Table [dbo].[DIMTARIFASCONTRATO]    Script Date: 12/06/2025 18:22:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIMTARIFASCONTRATO](
	[ID_CONTRATO] [int] NOT NULL,
	[ID_BANCO] [int] NULL,
	[COD_OCORRENCIA] [varchar](2) NULL,
	[VL_TARIFA_CONTRATO] [numeric](16, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CONTRATO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [DM_CNAB]
GO

/****** Object:  Table [dbo].[DIMTEMPO]    Script Date: 12/06/2025 18:22:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIMTEMPO](
	[IDDATA] [int] NOT NULL,
	[DATA] [datetime] NULL,
	[ANO] [int] NULL,
	[MES] [int] NULL,
	[DIA] [int] NULL,
	[SEMESTRE] [int] NULL,
	[TRIMESTRE] [int] NULL,
	[NOME_MES] [varchar](20) NULL,
	[NOME_DIA_SEMANA] [varchar](20) NULL,
	[EH_FINAL_DE_SEMANA] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[IDDATA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [DM_CNAB]
GO

/****** Object:  Table [dbo].[DIMTITULOS]    Script Date: 12/06/2025 18:22:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIMTITULOS](
	[ID_DUPLICATA] [int] NOT NULL,
	[DUPLICATA] [varchar](20) NULL,
	[NOSSO_NUMERO] [varchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_DUPLICATA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [DM_CNAB]
GO

/****** Object:  Table [dbo].[FACTCNAB]    Script Date: 12/06/2025 18:23:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FACTCNAB](
	[ID_ARQUIVO] [int] NULL,
	[ID_BANCO] [int] NULL,
	[DT_GERACAO] [int] NULL,
	[DT_OCORRENCIA] [int] NULL,
	[DT_CREDITO] [int] NULL,
	[DT_VENCIMENTO] [int] NULL,
	[ID_DUPLICATA] [int] NULL,
	[ID_OCORRENCIA] [int] NULL,
	[ID_CONTRATO] [int] NULL,
	[VL_TITULO] [numeric](16, 2) NULL,
	[VL_JUROS_MORA] [numeric](16, 2) NULL,
	[VL_PAGO] [numeric](16, 2) NULL,
	[VL_TARIFA] [numeric](16, 2) NULL,
	[VL_DESCONTO] [numeric](16, 2) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([DT_CREDITO])
REFERENCES [dbo].[DIMTEMPO] ([IDDATA])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([DT_GERACAO])
REFERENCES [dbo].[DIMTEMPO] ([IDDATA])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([DT_OCORRENCIA])
REFERENCES [dbo].[DIMTEMPO] ([IDDATA])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([DT_VENCIMENTO])
REFERENCES [dbo].[DIMTEMPO] ([IDDATA])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([ID_ARQUIVO])
REFERENCES [dbo].[DIMARQUIVO] ([ID_ARQUIVO])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([ID_BANCO])
REFERENCES [dbo].[DIMBANCOS] ([ID_BANCO])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([ID_CONTRATO])
REFERENCES [dbo].[DIMTARIFASCONTRATO] ([ID_CONTRATO])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([ID_DUPLICATA])
REFERENCES [dbo].[DIMTITULOS] ([ID_DUPLICATA])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([ID_OCORRENCIA])
REFERENCES [dbo].[DIMOCORRENCIAS] ([ID_OCORRENCIA])
GO

