USE [DM_CNAB]
GO

/****** Object:  Table [dbo].[DIMTARIFASCONTRATO]    Script Date: 12/06/2025 18:22:10 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIMTARIFASCONTRATO](
	[ID_CONTRATO] [int] NOT NULL,
	[ID_BANCO] [int] NULL,
	[COD_OCORRENCIA] [varchar](2) NULL,
	[VL_TARIFA_CONTRATO] [numeric](16, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_CONTRATO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

