USE [DM_CNAB]
GO

/****** Object:  Table [dbo].[DIMARQUIVO]    Script Date: 12/06/2025 18:21:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIMARQUIVO](
	[ID_ARQUIVO] [int] NOT NULL,
	[NOMEARQUIVO] [varchar](200) NULL,
	[ID_BANCO] [int] NULL,
	[CODIGO_BANCO] [varchar](3) NULL,
	[NOME_BANCO] [varchar](150) NULL,
	[DTGERACAO] [datetime] NULL,
	[DTINCLUIU] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ARQUIVO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

