USE [DM_CNAB]
GO

/****** Object:  Table [dbo].[DIMOCORRENCIAS]    Script Date: 12/06/2025 18:21:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIMOCORRENCIAS](
	[ID_OCORRENCIA] [int] NOT NULL,
	[ID_BANCO] [int] NULL,
	[COD_OCORRENCIA] [varchar](2) NULL,
	[DESC_OCORRENCIA] [varchar](150) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_OCORRENCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

