USE [DM_CNAB]
GO

/****** Object:  Table [dbo].[DIMTEMPO]    Script Date: 12/06/2025 18:22:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIMTEMPO](
	[IDDATA] [int] NOT NULL,
	[DATA] [datetime] NULL,
	[ANO] [int] NULL,
	[MES] [int] NULL,
	[DIA] [int] NULL,
	[SEMESTRE] [int] NULL,
	[TRIMESTRE] [int] NULL,
	[NOME_MES] [varchar](20) NULL,
	[NOME_DIA_SEMANA] [varchar](20) NULL,
	[EH_FINAL_DE_SEMANA] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[IDDATA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

