USE [DM_CNAB]
GO

/****** Object:  Table [dbo].[FACTCNAB]    Script Date: 12/06/2025 18:23:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FACTCNAB](
	[ID_ARQUIVO] [int] NULL,
	[ID_BANCO] [int] NULL,
	[DT_GERACAO] [int] NULL,
	[DT_OCORRENCIA] [int] NULL,
	[DT_CREDITO] [int] NULL,
	[DT_VENCIMENTO] [int] NULL,
	[ID_DUPLICATA] [int] NULL,
	[ID_OCORRENCIA] [int] NULL,
	[ID_CONTRATO] [int] NULL,
	[VL_TITULO] [numeric](16, 2) NULL,
	[VL_JUROS_MORA] [numeric](16, 2) NULL,
	[VL_PAGO] [numeric](16, 2) NULL,
	[VL_TARIFA] [numeric](16, 2) NULL,
	[VL_DESCONTO] [numeric](16, 2) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([DT_CREDITO])
REFERENCES [dbo].[DIMTEMPO] ([IDDATA])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([DT_GERACAO])
REFERENCES [dbo].[DIMTEMPO] ([IDDATA])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([DT_OCORRENCIA])
REFERENCES [dbo].[DIMTEMPO] ([IDDATA])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([DT_VENCIMENTO])
REFERENCES [dbo].[DIMTEMPO] ([IDDATA])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([ID_ARQUIVO])
REFERENCES [dbo].[DIMARQUIVO] ([ID_ARQUIVO])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([ID_BANCO])
REFERENCES [dbo].[DIMBANCOS] ([ID_BANCO])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([ID_CONTRATO])
REFERENCES [dbo].[DIMTARIFASCONTRATO] ([ID_CONTRATO])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([ID_DUPLICATA])
REFERENCES [dbo].[DIMTITULOS] ([ID_DUPLICATA])
GO

ALTER TABLE [dbo].[FACTCNAB]  WITH CHECK ADD FOREIGN KEY([ID_OCORRENCIA])
REFERENCES [dbo].[DIMOCORRENCIAS] ([ID_OCORRENCIA])
GO

