USE [DM_CNAB]
GO

/****** Object:  Table [dbo].[DIMBANCOS]    Script Date: 12/06/2025 18:21:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIMBANCOS](
	[ID_BANCO] [int] NOT NULL,
	[CODIGO_BANCO] [varchar](3) NULL,
	[NOME_BANCO] [varchar](60) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_BANCO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

