
--COLOCAR O CAMPO EXPORTADO = 'N' DE NÃO PARA CONSEGUIR EXECUTAR A PROCEDURE E POPULAR O STG_CNAB
--NO CASO DE TER A BASE STG_CNAB LIMPA PRECISA EXECUTAR O COMANDO NA BASE CNAB
UPDATE USR_CRRET SET EXPORTADO = 'N' WHERE EXPORTADO = 'S';

